Traceback (most recent call last):
  File "/home/F3/src/efsolver.py", line 139, in efsolve
    eval_phi = solve_with_timeout(get_timeout(),
  File "/home/F3/src/solver.py", line 123, in solve_with_timeout
    return solver.solve(assumptions)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/solver.py", line 351, in solve
    res = self._solve(assumptions=assumptions)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/z3.py", line 214, in _solve
    raise SolverReturnedUnknownResultError
pysmt.exceptions.SolverReturnedUnknownResultError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/F3/src/run_f3.py", line 444, in <module>
    main(config_args().parse_args())
  File "/home/F3/src/run_f3.py", line 440, in main
    run_f3(bench, out_dir)
  File "/home/F3/src/run_f3.py", line 260, in run_f3
    res = solve_problem(prob, label, out_dir)
  File "/home/F3/src/run_f3.py", line 251, in solve_problem
    return run_ltl_test(problem, env, label, out_dir)
  File "/home/F3/src/run_f3.py", line 113, in run_ltl_test
    return search_nonterm(env, symbols, init, trans, fairness,
  File "/home/F3/src/run_f3.py", line 169, in search_nonterm
    _, arg0, arg1 = search_funnel_bmc(env, symbols, init, trans,
  File "/home/F3/src/main.py", line 250, in search_funnel_bmc
    is_rf, args = rf_or_funnel_from_trace(env, symbols, trace, abst_path,
  File "/home/F3/src/main.py", line 550, in rf_or_funnel_from_trace
    rank_rel = instantiate_rf_template(ranker, rank_t, all_states,
  File "/home/F3/src/main.py", line 658, in instantiate_rf_template
    model, learn = ranker.ef_instantiate(rf, states, trans)
  File "/home/F3/src/ranker.py", line 183, in ef_instantiate
    res, c_learn = efsolve(self.env, rf.params, symbs,
  File "/home/F3/src/efsolver.py", line 147, in efsolve
    esolver.push()
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/solver.py", line 365, in push
    self._push(levels=levels)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/z3.py", line 264, in _push
    self.z3.push()
  File "/usr/local/lib/python3.8/dist-packages/z3/z3.py", line 6529, in push
    Z3_solver_push(self.ctx.ref(), self.solver)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 3742, in Z3_solver_push
    _elems.f(a0, a1)
KeyboardInterrupt
real 3602.13
user 0.00
sys 0.00
