Traceback (most recent call last):
  File "/home/F3/src/multisolver.py", line 97, in solve
    res = self._c_solver.timeout_solve(assumptions=assumptions)
  File "/home/F3/src/multisolver.py", line 191, in solver_timeout_solve
    return self.solve(assumptions)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/solvers/solver.py", line 351, in solve
    res = self._solve(assumptions=assumptions)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/solvers/msat.py", line 271, in _solve
    raise SolverReturnedUnknownResultError(msat_msg)
pysmt.exceptions.SolverReturnedUnknownResultError: user-requested termination

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/F3/src/run_f3.py", line 436, in <module>
    main(config_args().parse_args())
  File "/home/F3/src/run_f3.py", line 432, in main
    run_f3(bench, out_dir)
  File "/home/F3/src/run_f3.py", line 260, in run_f3
    res = solve_problem(prob, label, out_dir)
  File "/home/F3/src/run_f3.py", line 251, in solve_problem
    return run_ltl_test(problem, env, label, out_dir)
  File "/home/F3/src/run_f3.py", line 113, in run_ltl_test
    return search_nonterm(env, symbols, init, trans, fairness,
  File "/home/F3/src/run_f3.py", line 169, in search_nonterm
    _, arg0, arg1 = search_unrank_bmc(env, symbols, init, trans,
  File "/home/F3/src/unranker.py", line 160, in search_unrank_bmc
    for i, (trace, lback_idx, abst_path, hints) in \
  File "/home/F3/src/abstract_loops.py", line 266, in gen_loops
    sat = solver.solve()
  File "/home/F3/src/multisolver.py", line 100, in solve
    self._c_solver.reset_assertions()
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/solvers/solver.py", line 325, in reset_assertions
    self._reset_assertions()
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev331-py3.8.egg/pysmt/solvers/msat.py", line 201, in _reset_assertions
    mathsat.msat_reset_env(self.msat_env())
  File "/usr/local/lib/python3.8/dist-packages/mathsat.py", line 1421, in msat_reset_env
    return _mathsat.msat_reset_env(e)
KeyboardInterrupt
real 3602.47
user 0.00
sys 0.00
