Traceback (most recent call last):
  File "/home/F3/src/run_f3.py", line 467, in <module>
    main(config_args().parse_args())
  File "/home/F3/src/run_f3.py", line 463, in main
    run_f3(bench, out_dir)
  File "/home/F3/src/run_f3.py", line 277, in run_f3
    res = solve_problem(prob, label, out_dir)
  File "/home/F3/src/run_f3.py", line 268, in solve_problem
    return run_ltl_test(problem, env, label, out_dir)
  File "/home/F3/src/run_f3.py", line 127, in run_ltl_test
    return search_nonterm(env, symbols, init, trans, fairness,
  File "/home/F3/src/run_f3.py", line 184, in search_nonterm
    _, arg0, arg1 = search_funnel_bmc(env, symbols, init, trans,
  File "/home/F3/src/main.py", line 260, in search_funnel_bmc
    is_rf, args = rf_or_funnel_from_trace(env, symbols, trace, abst_path,
  File "/home/F3/src/main.py", line 714, in rf_or_funnel_from_trace
    model = instantiate_funnel_template(nontermarg)
  File "/home/F3/src/main.py", line 786, in instantiate_funnel_template
    model = funnel_t.motzkin_instantiate(extra=learn if get_fun_learn_ef()
  File "/home/F3/src/funnel.py", line 680, in motzkin_instantiate
    solver.add_assertion(c)
  File "/home/F3/src/multisolver.py", line 160, in add_assertion
    s.add_assertion(formula, named=named)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/solver.py", line 342, in add_assertion
    tracked = self._add_assertion(formula, named=named)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/z3.py", line 186, in _add_assertion
    self.z3.add(term)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3.py", line 6613, in add
    self.assert_exprs(*args)
  File "/usr/local/lib/python3.8/dist-packages/z3/z3.py", line 6602, in assert_exprs
    Z3_solver_assert(self.ctx.ref(), self.solver, arg.as_ast())
  File "/usr/local/lib/python3.8/dist-packages/z3/z3core.py", line 3759, in Z3_solver_assert
    _elems.f(a0, a1, a2)
KeyboardInterrupt
real 3602.46
user 0.00
sys 0.00
